### ISSUE TITLE
模型每次生成的回复不一样啊

### ISSUE THREAD

**Issue by chongzicbo** [shibing624/dialogbot#3]
老师您好，同样的query，模型每次生成的response不同，什么原因呢？

**Comment by shibing624** [comment]
默认设置了topk呀

**Comment by shirubei** [comment]
我感觉每次生成一样的就太没意思了，就是要有点变化。比如闲聊的功能，每次都回答相同的话，听话的人会觉得很无聊，被敷衍了。
